#!/bin/sh /etc/rc.common

START=96
STOP=10
USE_PROCD=1

start_service() {
	config_load dw5934e-autonet
	config_get_bool enabled main enabled 1
	[ "$enabled" = 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/dw5934e-autonet daemon
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger dw5934e-autonet
}

status_service() {
	/usr/sbin/dw5934e-autonet status
}
